// Generated by https://quicktype.io

export interface CharacterSearchResult {
    Pagination: Pagination;
    Results:    CharacterSearch[];
}

export interface Pagination {
    Page:           number;
    PageNext:       null;
    PagePrev:       null;
    PageTotal:      number;
    Results:        number;
    ResultsPerPage: number;
    ResultsTotal:   number;
}

export interface CharacterSearch {
    Avatar:       string;
    FeastMatches: number;
    ID:           number;
    Lang:         string;
    Name:         string;
    Rank:         null;
    RankIcon:     null;
    Server:       string;
}
