// Generated by https://quicktype.io

export interface ClassJobResult {
    Pagination: Pagination;
    Results:    ClassJob[];
}

export interface Pagination {
    Page:           number;
    PageNext:       null;
    PagePrev:       null;
    PageTotal:      number;
    Results:        number;
    ResultsPerPage: number;
    ResultsTotal:   number;
}

export interface ClassJob {
    ID:   number;
    Icon: string;
    Name: string;
    Url:  string;
}
