// Generated by https://quicktype.io

export interface Season {
    id:     number;
    name:   string;
    start:  number;
    end:    number;
    region: Region;
}

export enum Region {
    Eu = "eu",
    Kr = "kr",
    Tw = "tw",
    Us = "us",
}
